# generated by datamodel-codegen:
#   filename:  APIStorageStatusRequest.schema.json
#   timestamp: 2024-04-23T13:27:51+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class StorageStatusRequest(BaseModel):
    vehicle: Optional[bool] = Field(
        None,
        description='Optional. Indicates whether to enable storage for the Vehicle API.',
    )
    transport: Optional[bool] = Field(
        None,
        description='Optional. Indicates whether to enable storage for the Transport API.',
    )
