# generated by datamodel-codegen:
#   filename:  OKResponse.schema.json
#   timestamp: 2024-05-14T11:09:50+00:00

from __future__ import annotations

from enum import Enum


class SuccessfulResponse(Enum):
    OK = 'OK'
