# generated by datamodel-codegen:
#   filename:  OKResponse.schema.json
#   timestamp: 2024-04-23T13:27:53+00:00

from __future__ import annotations

from enum import Enum


class SuccessfulResponse(Enum):
    OK = 'OK'
