# generated by datamodel-codegen:
#   filename:  UpdateHookRequest.schema.json
#   timestamp: 2024-04-23T13:27:53+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class UpdateHookRequest(BaseModel):
    vehicle: Optional[bool] = Field(
        None, description='Optional. Indicates whether to subscribe to the Vehicle API.'
    )
    transport: Optional[bool] = Field(
        None,
        description='Optional. Indicates whether to subscribe to the Transport API.',
    )
