# generated by datamodel-codegen:
#   filename:  DimensionListReponse.schema.json
#   timestamp: 2024-05-14T11:09:56+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Dimension(BaseModel):
    id: str = Field(
        ..., description='The unique identifier of the dimension.', title='Dimension ID'
    )
    name: str = Field(
        ..., description='The display name of the dimension.', title='Dimension Name'
    )
    requestCount: float = Field(
        ...,
        description='The number of API requests included in the dimension.',
        title='Request Count',
    )


class Dimensions(BaseModel):
    __root__: List[Dimension] = Field(
        ...,
        description='An array of available subscription dimensions.',
        title='Dimensions',
    )
