# generated by datamodel-codegen:
#   filename:  PaidSubscriptionUsageResponse.schema.json
#   timestamp: 2024-05-14T11:09:57+00:00

from __future__ import annotations

from datetime import date
from typing import List

from pydantic import BaseModel, Field


class PaidSubscriptionUsages(BaseModel):
    startTime: date = Field(
        ...,
        description='The start of the time interval queried as a millisecond timestamp, not older than 90 days.',
        title='Start Time',
    )
    endTime: date = Field(
        ...,
        description='The end of the time interval queried as a millisecond timestamp.',
        title='End Time',
    )
    usages: List[float] = Field(
        ...,
        description='Lists the number of credits used for each day of the interval queried. The sum of this array is the total number of credits used in the interval queried.',
        title='Usages',
    )
