# generated by datamodel-codegen:
#   filename:  ProductsResponse.schema.json
#   timestamp: 2024-05-14T11:09:58+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Product(BaseModel):
    id: str = Field(
        ..., description='The unique identifier of this product.', title='ID'
    )
    name: str = Field(
        ...,
        description='The human-readable display name of this product.',
        title='Name',
    )
    stripeProductCode: str = Field(
        ...,
        description='The Stripe product code associated with this product.',
        title='Stripe Product Code',
    )
    stripeUsagesProductCode: str = Field(
        ...,
        description='The Stripe product code used for metering usage for this product.',
        title='Stripe Usages Product Code',
    )
    marketplaceProductCode: str = Field(
        ...,
        description='The AWS Marketplace product code associated with this product.',
        title='Marketplace Product Code',
    )


class Products(BaseModel):
    __root__: List[Product] = Field(
        ...,
        description='An array of products a suer can subscribe to.',
        title='Products',
    )
